name: Publish GitHub Pages Manually

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Generate Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: docs/Doxygen/Doxyfile
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          destination_dir: docs
          force_orphan: true